name: Docker

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: mostefaiamine/demo2022

jobs:
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v2
      - name: Build image
        run: docker build . --file ./MoviesFan/Dockerfile --tag $IMAGE_NAME:${{ github.run_number }}
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.HUB_TOKEN }}
      - name: Push images
        run: |
          docker tag $IMAGE_NAME:${{ github.run_number }} $IMAGE_NAME:latest
          docker push $IMAGE_NAME:${{ github.run_number }}
          docker push $IMAGE_NAME:latest
